// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbaphgfxqooishhfsllg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiYXBoZ2Z4cW9vaXNoaGZzbGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTkyODksImV4cCI6MjA2MjQ3NTI4OX0.j153NhRoWAwOuv1J4ODBtsaDQmLFjbCTyT4vjHCxLVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);